# Structure of this file matters, but order does not.
# id: some id
# name: some name
#
# and
# name: some name
# id: some id
#
# produce the same result.
# person:
#   name: some name
#
# and 
# 
#   name: some name
# person:
# do not.

# This tells CAST which metadata importer to use.
data source: RASL

# Speaker id is used in the output csv file.
speaker id: 12532 f
# This is where we read the wavs and metadata from.
data directory: small/12532 (f)/Session2
# This will be used as the name of the output wav and TextGrid.
outputfilename: small/12532 (f)/Session2/12532 (f) Session2 concatenated_recordings

flags:
  detect beep: False # Should onset beep detection be run?
  utterance: False # Add Utterance Tier.
  file: True # Add File Tier.
  only words: True # Add only Utterance and Word Tiers.
  test: False # Run on only the first 10 recordings.

# Strict YAML file specifying recordings to be excluded based 
# on both prompts and file names.
exclusion list: 

# Consists of words followed by their segments in arbitrary transcription. 
# When only words is True this can be omitted.
pronunciation dictionary: local_data/GFTA_phonemes_in_words_in_SAMPA.csv

# Start and end points of the guess where the word or speech might 
# be in normalised time. If beep detection is used the normalised
# period runs from end of beep to end of recording.
word guess:
  begin: 0.33
  end: 0.5
