exclusion list: cast_exclude_example.yml
pronunciation dictionary: local_data/gam_mono_and_disyllables_for_automatic_segmentation.csv
outputfilename: local_data/gam-1-2-test

options:
  detect_beep: True
  only_words: False
  test: True

word guess:
  begin: 0.0833
  end: 0.6667
