# Speaker id is used in the output csv file.
speaker id: gam-1-2
# This is where we read the wavs and metadata from.
data directory: local_data/gam-1-2
# This will be used as the name of the output wav and TextGrid.
outputfilename: local_data/gam-1-2-test

flags:
  detect beep: False # Should onset beep detection be run?
  only words: True # Add only Utterance and Word Tiers.
  test: True # Run on only the first 10 recordings.

# Strict YAML file specifying recordings to be excluded based 
# on both prompts and file names.
exclusion list: cast_exclude_example.yml
# Consists of words followed by their segments in arbitrary transcription.  
pronunciation dictionary: local_data/gam_mono_and_disyllables_for_automatic_segmentation.csv

# Start and end points of the guess where the word or speech might 
# be in normalised time. If beep detection is used the normalised
# period runs from end of beep to end of recording.
word guess:
  begin: 0.5
  end: 0.7
