[project]
name = "computer-assisted-segmentation-tools"
version = "0.2.0"
description = "Add a short description here"
authors = ["Pertti Palo <giuthas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
