[project]
name = "computer-assisted-segmentation-tools"
version = "0.2.0"
description = "CAST - Computer Assisted Segmentation Tools"
authors = ["Pertti Palo <giuthas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
pydantic = ">=2.9.2,<3"
pixi-pycharm = ">=0.0.7,<0.0.8"
strictyaml = ">=1.7.3,<2"
numpy = ">=2.1.2,<3"
scipy = ">=1.14.1,<2"
matplotlib = ">=3.9.2,<4"

[pypi-dependencies]
computer-assisted-segmentation-tools = { path = ".", editable = true }
praat-textgrids = ">=1.4.0, <2"

[feature.devel.dependencies]
pylint = ">=2.7.2,<3.3"
autopep8 = ">=1.3.2,<2.4"
icecream = ">=2.1.3,<2.2"

[feature.devel.pypi-dependencies]
licenseheaders = ">=0.8.8, <0.9"

[environments]
devel = ["devel"]
