[project]
name = "computer-assisted-segmentation-tools"
version = "0.1.0"
description = "CAST - Computer Assisted Segmentation Tools"
authors = [
    {name = "Pertti Palo", email = "giuthas@gmail.com"}
]
license = "GPL-3.0"
readme = "README.markdown"
requires-python = ">=3.10,<3.13"
dependencies = []

[project.scripts]
cast = "source.cast:run_cli"
computer-assisted-segmentation-tools = "source.cast:run_cli"

[tool.pixi.project]
channels = ["default", "conda-forge"]
platforms = ["linux-64"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "/source",
]

[tool.pixi.pypi-dependencies]
pixi-py = { path = ".", editable = true }

[tool.pixi.tasks]