[project]
name = "textgrid-gen"
version = "0.3.0"
description = "TextGrid-Gen: Autogenerate TextGrids for humans to edit"
readme = "README.md"
authors = [
    { name = "Pertti Palo", email = "giuthas@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "praat-textgrids>=1.4.0",
    "pydantic>=2.13.4",
    "pylint>=4.0.7",
    "scipy>=1.15.3",
    "strictyaml>=1.7.3",
    "tqdm>=4.70.0",
]

[project.scripts]
textgrid-gen = "textgrid_gen:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "icecream>=2.2.0",
    "licenseheaders>=0.8.8",
]
